version: '3'

services:

  lint:
    build:
      context: ./
      args:
        environment: development
    #CI can't mount volumes!
    #volumes:
    #  - ./.eslintrc:/usr/local/app/.eslintrc
    #  - ./lib:/usr/local/app/lib
    command: npm run lint

  app:
    build:
      context: ./
      args:
        environment: development
    container_name: hapi-app
    volumes:
      - ./package.json:/usr/local/app/package.json
      - ./lib:/usr/local/app/lib
      - ./.eslintrc:/usr/local/app/.eslintrc
    working_dir: /usr/local/app
    ports:
      - "8080:8080"
    environment:
      APP_DB_NAME: app
      APP_DB_USERNAME: test
      APP_DB_PASSWORD: test
      MONGO_URL: db
    depends_on:
      - db
    restart: unless-stopped
    command:
      npm run serve

  db:
    image: singh1469/hapi-playground-db
    container_name: db
    environment:
      MONGO_PASSWORD: admin
      APP_DB_NAME: app
      APP_USERNAME: test
      APP_PASSWORD: test
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/app --quiet
      interval: 2s
      timeout: 3s
      retries: 5
    volumes:
      - ./dev/mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "27017:27017"
