version: '3'

services:

  app:
    image: singh1469/hapi-playground:0.1.40
    container_name: hapi-app
    working_dir: /usr/local/app
    ports:
      - "8080:8080"
    environment:
      APP_DB_NAME: app
      APP_DB_USERNAME: test
      APP_DB_PASSWORD: test
      MONGO_URL: db
    depends_on:
      - db
    restart: unless-stopped
    command:
      npm run prod

  db:
    image: singh1469/hapi-playground-db:0.1.2
    container_name: db
    environment:
      MONGO_PASSWORD: admin
      APP_DB_NAME: app
      APP_USERNAME: test
      APP_PASSWORD: test
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/app --quiet
      interval: 2s
      timeout: 3s
      retries: 5
    ports:
      - "27017:27017"
