version: 2
jobs:
  lint:
    working_directory: ~/hapi-playground
    docker:
      - image: docker:stable-git
    steps:
      - run:
          name: Install Make
          command: |
            apk add --update make
      - run:
          name: Install Curl
          command: |
            apk add --update curl
      - run:
          name: Install PIP
          command: |
            apk add --no-cache python3 && \
            python3 -m ensurepip && \
            rm -r /usr/lib/python*/ensurepip && \
            pip3 install --upgrade pip setuptools && \
            if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
            if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
            rm -r /root/.cache
      - run:
          name: Install docker-compose
          command: |
            pip install docker-compose
      - setup_remote_docker
      - checkout
      - run:
          name: Docker-compose build
          command: |
            make build-compose
      - run:
          name: Running lint
          command: make lint
  build:
    working_directory: ~/hapi-playground
    docker:
      - image: docker:stable-git
    steps:
      - run:
          name: Install Make
          command: |
            apk add --update make
      - setup_remote_docker
      - checkout
      - run:
          name: Build artifact
          command: |
            make build-artifact
workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build:
          requires:
            - lint
