version: 2
jobs:
  build:
    working_directory: ~/my-app
    docker:
      - image: docker:stable-git
    steps:
      - run:
          name: Install Make
          command: |
            apk add --update make
      - run:
          name: Install Curl
          command: |
            apk add --update curl
      - run:
          name: Install PIP
          command: |
            apk add --no-cache python3 && \
            python3 -m ensurepip && \
            rm -r /usr/lib/python*/ensurepip && \
            pip3 install --upgrade pip setuptools && \
            if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
            if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
            rm -r /root/.cache
      - run:
          name: Install docker-compose
          command: |
            pip install docker-compose
      - setup_remote_docker
      - checkout
      - run:
          name: Running lint
          command: cd ~/my-app && make lint
