---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-api
  namespace: {{.Values.ns}}
  labels:
    app: svc-api
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: pod-api
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{.Values.appName}}-api
  namespace: {{.Values.ns}}
  labels:
    app: pod-api
spec:
  replicas: 1
  selector:
      matchLabels:
        app: pod-api
  template:
    metadata:
      labels:
        app: pod-api
    spec:
      containers:
      - name: {{.Values.appName}}-api
        image: singh1469/hapi-playground:{{.Values.dockerTagApi}}
        ports:
        - containerPort: 8080
